# Generated by Django 4.2.4 on 2023-11-27 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mart', '0004_return_issue'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_price', models.FloatField()),
                ('extra_cost', models.FloatField(blank=True, null=True)),
                ('paid', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('is_refill', models.BooleanField()),
                ('is_wholesale', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mart.product')),
            ],
        ),
    ]
