# Generated by Django 4.2.4 on 2023-11-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gross', '0002_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='due',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
