# Generated by Django 4.2.4 on 2023-11-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0002_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='is_refill',
        ),
    ]
